name: smart_trip_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0


isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  google_fonts: ^6.3.1
  hooks_riverpod: ^2.6.1
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.1.5
  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_functions: ^5.1.3
  # cloud_firestore: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.6.4
  build_runner: any
  isar_generator: *isar_version

flutter:
  uses-material-design: true
